#!/usr/bin/env bash
# luks.sh — Chroot-side LUKS wiring: crypttab, initramfs, keyfile, GRUB.
#
# The container itself is created in lib/disk.sh (outer process, where the
# passphrase lives). This module makes the installed system able to open it at
# boot, which on Void means three separate things:
#
#   1. /etc/crypttab — what dracut reads to know a container exists
#   2. /etc/dracut.conf.d — the `crypt` module plus the keyfile, both of which
#      have to be inside the initramfs image
#   3. /etc/default/grub — GRUB_ENABLE_CRYPTODISK, because /boot lives on the
#      encrypted root: GRUB must open the container to read the kernel at all
#
# The two-passphrase problem: GRUB asks once to read /boot, then the initramfs
# asks again to mount root. A keyfile embedded in the initramfs removes the
# second prompt. That is only safe because the initramfs itself sits on the
# encrypted root — hence the hard guard against a separate /boot.
source "${LIB_DIR}/protection.sh"

# Where the outer process leaves the keyfile it already added to the container.
: "${LUKS_KEYFILE_STAGE:=/tmp/void-installer-luks.key}"
: "${LUKS_KEYFILE_TARGET:=/boot/luks-keyfile}"

# luks_configure_system — Entry point for the chroot phase.
luks_configure_system() {
    [[ "${LUKS_ENABLED:-no}" == "yes" ]] || return 0

    einfo "Configuring LUKS support in the installed system..."

    try "Installing cryptsetup" xbps-install -y cryptsetup

    _luks_write_crypttab
    _luks_install_keyfile
    _luks_write_dracut_conf

    einfo "LUKS configuration complete"
}

# _luks_write_crypttab — Name the container by UUID, never by device path
# (/dev/sda2 moves the moment a USB disk is plugged in at boot).
_luks_write_crypttab() {
    local name="${LUKS_NAME:-cryptroot}"
    local luks_uuid
    luks_uuid=$(get_uuid "${LUKS_PARTITION}")

    if [[ -z "${luks_uuid}" ]]; then
        eerror "Cannot read UUID of LUKS partition ${LUKS_PARTITION}"
        return 1
    fi

    local keyfile_field="none"
    if [[ -f "${LUKS_KEYFILE_STAGE}" ]] && _luks_keyfile_is_safe; then
        keyfile_field="${LUKS_KEYFILE_TARGET}"
    fi

    printf '%s UUID=%s %s luks\n' "${name}" "${luks_uuid}" "${keyfile_field}" \
        > /etc/crypttab
    chmod 600 /etc/crypttab

    einfo "  /etc/crypttab: ${name} -> UUID=${luks_uuid} (key: ${keyfile_field})"
}

# _luks_keyfile_is_safe — The keyfile trick is only acceptable while the
# initramfs is on the encrypted root. With a separate unencrypted /boot the
# key would sit in the clear next to the data it unlocks, so refuse it.
_luks_keyfile_is_safe() {
    if [[ -n "${BOOT_PARTITION:-}" ]]; then
        ewarn "Separate /boot partition — skipping keyfile (it would be unencrypted)"
        return 1
    fi
    return 0
}

# _luks_install_keyfile — Move the staged keyfile into the target system.
_luks_install_keyfile() {
    [[ -f "${LUKS_KEYFILE_STAGE}" ]] || {
        einfo "  No keyfile staged — the passphrase will be asked twice at boot"
        return 0
    }

    if ! _luks_keyfile_is_safe; then
        shred -u "${LUKS_KEYFILE_STAGE}" 2>/dev/null || rm -f "${LUKS_KEYFILE_STAGE}"
        return 0
    fi

    install -m 000 "${LUKS_KEYFILE_STAGE}" "${LUKS_KEYFILE_TARGET}" \
        || { ewarn "Could not install LUKS keyfile"; return 0; }

    shred -u "${LUKS_KEYFILE_STAGE}" 2>/dev/null || rm -f "${LUKS_KEYFILE_STAGE}"
    einfo "  Keyfile installed at ${LUKS_KEYFILE_TARGET} (mode 000, on encrypted root)"
}

# _luks_write_dracut_conf — Pull the crypt module and the keyfile into every
# initramfs dracut builds from now on, including the ones generated by future
# kernel updates.
_luks_write_dracut_conf() {
    mkdir -p /etc/dracut.conf.d

    {
        echo "# LUKS support — written by the Void installer"
        echo 'add_dracutmodules+=" crypt "'
        if [[ -f "${LUKS_KEYFILE_TARGET}" ]]; then
            # install_items puts the file inside the image; without it
            # rd.luks.key points at a path that does not exist in early boot.
            echo "install_items+=\" ${LUKS_KEYFILE_TARGET} \""
        fi
    } > /etc/dracut.conf.d/10-luks.conf

    einfo "  dracut configured for LUKS"

    # Rebuild now — the initramfs generated before this config existed cannot
    # open the container.
    local kver
    kver=$(ls -1 /lib/modules 2>/dev/null | sort -V | tail -1) || true
    if [[ -n "${kver}" ]]; then
        try "Regenerating initramfs with LUKS support" \
            dracut --force "/boot/initramfs-${kver}.img" "${kver}"
    else
        ewarn "No kernel modules directory found — initramfs not regenerated"
    fi
}

# luks_grub_cmdline — Kernel cmdline fragment for the encrypted root.
# Echoed into GRUB_CMDLINE_LINUX by lib/bootloader.sh.
luks_grub_cmdline() {
    [[ "${LUKS_ENABLED:-no}" == "yes" ]] || return 0

    local luks_uuid
    luks_uuid=$(get_uuid "${LUKS_PARTITION}")
    [[ -n "${luks_uuid}" ]] || return 0

    local params="rd.luks.uuid=${luks_uuid}"
    if [[ -f "${LUKS_KEYFILE_TARGET}" ]]; then
        params+=" rd.luks.key=${LUKS_KEYFILE_TARGET}"
    fi

    printf '%s' "${params}"
}
