#!/usr/bin/env bash
# system.sh — System configuration for Void Linux
source "${LIB_DIR}/protection.sh"

# system_set_timezone — Configure timezone
system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"

    # Validate timezone
    if [[ ! -f "/usr/share/zoneinfo/${tz}" ]]; then
        ewarn "Invalid timezone '${tz}', falling back to UTC"
        tz="UTC"
    fi

    einfo "Setting timezone: ${tz}"

    # Void uses /etc/localtime symlink
    ln -sf "/usr/share/zoneinfo/${tz}" /etc/localtime

    # Also write to /etc/timezone for reference
    echo "${tz}" > /etc/timezone

    einfo "Timezone set to ${tz}"
}

# system_set_locale — Configure locale
system_set_locale() {
    local locale="${LOCALE:-en_US.UTF-8}"
    einfo "Setting locale: ${locale}"

    # Enable locale in libc-locales
    local locales_file="/etc/default/libc-locales"
    if [[ -f "${locales_file}" ]]; then
        # Uncomment the desired locale
        sed -i "s/^#\(${locale}\)/\1/" "${locales_file}"
        # Also enable en_US.UTF-8 as fallback if not already the primary
        if [[ "${locale}" != "en_US.UTF-8" ]]; then
            sed -i 's/^#\(en_US\.UTF-8\)/\1/' "${locales_file}"
        fi
    else
        mkdir -p "$(dirname "${locales_file}")"
        echo "${locale} UTF-8" > "${locales_file}"
        echo "en_US.UTF-8 UTF-8" >> "${locales_file}"
    fi

    # Set system locale
    echo "LANG=${locale}" > /etc/locale.conf

    # Reconfigure glibc-locales to generate locales (skip on musl)
    if xbps-query glibc-locales &>/dev/null; then
        try "Generating locales" xbps-reconfigure -f glibc-locales
    fi

    einfo "Locale set to ${locale}"
}

# system_set_hostname — Configure hostname
system_set_hostname() {
    local hostname="${HOSTNAME:-void}"

    # Validate hostname (RFC 1123: alphanumeric + hyphens, no leading/trailing hyphen)
    if [[ ! "${hostname}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
        ewarn "Invalid hostname '${hostname}', falling back to 'void'"
        hostname="void"
    fi

    einfo "Setting hostname: ${hostname}"

    echo "${hostname}" > /etc/hostname

    # Update /etc/hosts
    cat > /etc/hosts <<EOF
127.0.0.1   localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
::1         localhost ip6-localhost ip6-loopback
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
EOF

    einfo "Hostname set to ${hostname}"
}

# system_set_keymap — Configure console keymap
system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    # Void uses /etc/rc.conf for keymap
    if [[ -f /etc/rc.conf ]]; then
        if grep -q '^KEYMAP=' /etc/rc.conf; then
            sed -i "s/^KEYMAP=.*/KEYMAP=\"${keymap}\"/" /etc/rc.conf
        else
            echo "KEYMAP=\"${keymap}\"" >> /etc/rc.conf
        fi
    else
        echo "KEYMAP=\"${keymap}\"" > /etc/rc.conf
    fi

    # Also set vconsole.conf for compatibility
    echo "KEYMAP=${keymap}" > /etc/vconsole.conf

    einfo "Keymap set to ${keymap}"
}

# generate_fstab — Generate /etc/fstab
generate_fstab() {
    einfo "Generating /etc/fstab..."

    local fstab="/etc/fstab"

    {
        echo "# /etc/fstab"
        echo "# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}"
        echo "#"
        echo "# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>"

        # Root filesystem
        local root_uuid
        root_uuid=$(get_uuid "${ROOT_PARTITION}") || true

        if [[ -n "${root_uuid}" ]]; then
            if [[ "${FILESYSTEM}" == "btrfs" && -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                local IFS=':'
                local -a parts
                read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                local idx
                for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                    local subvol="${parts[$idx]}"
                    local mpoint="${parts[$((idx + 1))]}"
                    local pass=2
                    [[ "${mpoint}" == "/" ]] && pass=1
                    echo "UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 ${pass}"
                done
            else
                echo "UUID=${root_uuid}   /             ${FILESYSTEM}    noatime,defaults        0 1"
            fi
        else
            echo "${ROOT_PARTITION}              /             ${FILESYSTEM:-ext4}     noatime,defaults        0 1"
        fi

        # ESP partition
        if [[ -n "${ESP_PARTITION:-}" ]]; then
            local esp_uuid
            esp_uuid=$(get_uuid "${ESP_PARTITION}") || true
            if [[ -n "${esp_uuid}" ]]; then
                echo "UUID=${esp_uuid}   /boot/efi     vfat    noatime,defaults        0 2"
            else
                echo "${ESP_PARTITION}              /boot/efi     vfat    noatime,defaults        0 2"
            fi
        fi

        # Swap partition
        if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
            local swap_uuid
            swap_uuid=$(get_uuid "${SWAP_PARTITION}") || true
            if [[ -n "${swap_uuid}" ]]; then
                echo "UUID=${swap_uuid}   none          swap    sw              0 0"
            else
                echo "${SWAP_PARTITION}              none          swap    sw              0 0"
            fi
        fi

        # tmpfs for /tmp
        echo "tmpfs                                   /tmp          tmpfs   defaults,nosuid,nodev   0 0"

    } > "${fstab}"

    einfo "fstab generated"
}

# install_filesystem_tools — Install filesystem utilities
install_filesystem_tools() {
    local fs="${FILESYSTEM:-ext4}"
    einfo "Installing filesystem tools for ${fs}..."

    local -a fs_pkgs=()

    case "${fs}" in
        ext4)   fs_pkgs+=("e2fsprogs") ;;
        btrfs)  fs_pkgs+=("btrfs-progs") ;;
        xfs)    fs_pkgs+=("xfsprogs") ;;
    esac

    # Always need dosfstools for ESP
    fs_pkgs+=("dosfstools")

    if [[ ${#fs_pkgs[@]} -gt 0 ]]; then
        try "Installing filesystem tools" xbps-install -y "${fs_pkgs[@]}"
    fi

    einfo "Filesystem tools installed"
}

# system_create_users — Create root password and user account
system_create_users() {
    einfo "Creating users..."

    # Set root password (pipe hash to avoid exposure in process list)
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        einfo "Setting root password"
        bash -c 'echo "root:$1" | chpasswd -e' -- "${ROOT_PASSWORD_HASH}"
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,input,storage,network}"

        # Filter out groups that don't exist on the target system
        local valid_groups=""
        local g
        IFS=',' read -ra _groups <<< "${groups}"
        for g in "${_groups[@]}"; do
            if getent group "${g}" &>/dev/null; then
                valid_groups+="${valid_groups:+,}${g}"
            else
                ewarn "Group '${g}' does not exist, skipping"
            fi
        done
        groups="${valid_groups:-wheel}"

        einfo "Creating user: ${USERNAME}"
        if ! id "${USERNAME}" &>/dev/null; then
            try "Creating user ${USERNAME}" \
                useradd -m -G "${groups}" -s /bin/bash "${USERNAME}"
        fi

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            try "Setting user password" \
                bash -c 'echo "$1:$2" | chpasswd -e' -- "${USERNAME}" "${USER_PASSWORD_HASH}"
        fi

        # Configure sudo
        try "Installing sudo" xbps-install -y sudo

        if [[ -f /etc/sudoers ]]; then
            # Ensure wheel group can sudo
            sed -i 's/^# \(%wheel ALL=(ALL:ALL) ALL\)/\1/' /etc/sudoers 2>/dev/null || true
            sed -i 's/^# \(%wheel ALL=(ALL) ALL\)/\1/' /etc/sudoers 2>/dev/null || true
        fi

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi
}

# _enable_service — Enable a runit service
_enable_service() {
    local service="$1"
    if [[ -d "/etc/sv/${service}" ]]; then
        ln -sf "/etc/sv/${service}" "/var/service/${service}" 2>/dev/null || true
        einfo "Enabled runit service: ${service}"
    else
        ewarn "Service not found: ${service}"
    fi
}

# system_finalize — Final system configuration
system_finalize() {
    einfo "Finalizing system..."

    # Reconfigure all packages (generates initramfs, locales, etc.)
    try "Reconfiguring all packages" xbps-reconfigure -fa

    # Enable essential services
    _enable_service "agetty-tty1"
    _enable_service "agetty-tty2"
    _enable_service "agetty-tty3"
    _enable_service "udevd"

    # Clean up
    checkpoint_clear
    rm -f /tmp/void-installer.conf

    einfo "System finalization complete"
}

# _install_gum_to_target — Copy bundled gum binary to installed system
# Runs OUTSIDE chroot (from run_post_install), uses MOUNTPOINT
_install_gum_to_target() {
    local target_bin="${MOUNTPOINT}/usr/local/bin"

    # Try cached gum first (already extracted during installer run)
    if [[ -x "${GUM_CACHE_DIR:-/tmp/void-installer-gum}/gum" ]]; then
        mkdir -p "${target_bin}"
        cp "${GUM_CACHE_DIR}/gum" "${target_bin}/gum" 2>/dev/null && \
            chmod +x "${target_bin}/gum" && \
            einfo "Installed gum to /usr/local/bin/gum"
        return 0
    fi

    # Try bundled tarball
    if [[ -f "${DATA_DIR:-}/gum.tar.gz" ]]; then
        local _gum_tmp
        _gum_tmp=$(mktemp -d)
        if tar xzf "${DATA_DIR}/gum.tar.gz" -C "${_gum_tmp}" 2>/dev/null; then
            local _gum_bin
            _gum_bin=$(find "${_gum_tmp}" -name "gum" -type f | head -1)
            if [[ -n "${_gum_bin}" ]]; then
                mkdir -p "${target_bin}"
                cp "${_gum_bin}" "${target_bin}/gum"
                chmod +x "${target_bin}/gum"
                einfo "Installed gum to /usr/local/bin/gum"
            fi
        fi
        rm -rf "${_gum_tmp}"
        return 0
    fi

    ewarn "Bundled gum not found — dotfiles wizard will download it on first run"
}
